# Site settings
title: Melanie VanderLugt
header-img: img/home-bg.jpg
email: melanie.vanderlugt@gmail.com
description: ""
baseurl: ""
url: "http://www.melanievanderlugt.com"
twitter_username: melanie_vee
github_username:  melanievee
facebook_username:  melanie.kreie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
